contact_links:
  - name: ğŸ“š Documentation
    url: https://content.nuxt.com/
    about: Check documentation for usage
  - name: âœï¸ Studio repository
    url: https://github.com/nuxt-content/nuxt-studio
    about: Feature request, report bug, â€¦
  - name: ğŸ’¬ Discussions
    url: https://github.com/nuxt/content/discussions
    about: Use discussions if you have an idea for improvement and asking questions
